### ISSUE TITLE
Creating CRDs with schema validation is broken

### ISSUE THREAD

**Issue by jkremser** [fabric8io/kubernetes-client#1486]
the K8s api server makes a lot of strict checks, for instance it fails if the schema contains default values, definitions, $ref elements, etc. One of the checks is:

```go
	if schema.Dependencies != nil {
		for dependency, jsonSchemaPropsOrStringArray := range schema.Dependencies {
			allErrs = append(allErrs, ValidateCustomResourceDefinitionOpenAPISchema(jsonSchemaPropsOrStringArray.Schema, fldPath.Child("dependencies").Key(dependency), ssv)...)
		}
	}
```

source: https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apis/apiextensions/validation/validation.go#L671

However, even if the `JSONSchemaProps` object has the `dependecies` field set to `null`, the object mapper from Jackson that's being used in [here](https://github.com/fabric8io/kubernetes-client/blob/a50f3e946f20b298f69f065a2597fc94a0cb2743/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L230) converts the `null` to an empty `LinkedHashMap` and this fails on the K8s api server. So there is no way currently to create the schema validation with the fabric8 k8s client.

I am using the `.withNewOpenAPIV3SchemaLike(schema)` method for the `CustomResourceDefinitionBuilder`.

I believe there must be some configuration of the object mapper so that it shouldn't translate nulls to empty maps.

```java
JSON_MAPPER.setSerializationInclusion(Include.NON_NULL);
```
..looks promising

**Comment by rohanKanojia** [comment]
@Jiri-Kremser : Hi, Could you please elaborate on your use case? What are you trying to do here? We're right now trying to simplify our Custom Resources support. We've introduced a new endpoint in our dsl which handles raw custom resources in form of hashmaps:

https://github.com/fabric8io/kubernetes-client/blob/a50f3e946f20b298f69f065a2597fc94a0cb2743/kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawCustomResourceIT.java#L60-L83

**Comment by Jiri-Kremser** [comment]
Cool, this looks  little bit easier than the `CustomResourceDefinitionBuilder`, but it doesn't support the OpenAPIV3Schema at all, so I guess it's less expressive than before. And the `CustomResourceDefinitionBuilder` is gone in the newest version.. does that mean that you are not going to support the open api v3 schemas at all or am I missing something?


> Could you please elaborate on your use case? 

sure, I want to create CRDs that have the OpenAPI Schema inside and make the validation for CRs working (https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation). The issue is (or at least with the previous version, where `CustomResourceDefinitionBuilder` was still there) that when using `CustomResourceDefinitionBuilder.withNewOpenAPIV3SchemaLike(JSONSchemaProps item)`, from some strange reason it didn't copied the `item` correctly to the `crdDef.spec.validation.schema`. If the original `JSONSchemaProps item` had the `item.dependencies` set to null, then after calling:

```java
...
builder.withNewOpenAPIV3SchemaLike(item)
...
builder.build()
```
The resulting CRD had the `"crd.spec.validation.schema.dependencies"` field set to an empty hash map (which failed on the k8s api).

I am currently using this hot-fix 

```java
crdToReturn.getSpec().getValidation().getOpenAPIV3Schema().setDependencies(null);
```

this works, but it doesn't seem right.

**Comment by rohanKanojia** [comment]
No no, this is an example of improved support for custom resources. For custom resource definitions it's still the same: 

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-itests/src/test/java/io/fabric8/kubernetes/CustomResourceDefinitionIT.java

**Comment by Jiri-Kremser** [comment]
here is the code if you need a bigger picture https://github.com/jvm-operators/abstract-operator/blob/master/src/main/java/io/radanalytics/operator/common/crd/CrdDeployer.java#L69

**Comment by rohanKanojia** [comment]
Hmm,  will try to reproduce your problem ....

**Comment by Jiri-Kremser** [comment]
here is the reproducer:

```java
public class Reproducer {

    public static JSONSchemaProps readSchema() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        URL in = Reproducer.class.getResource("/sparkCluster.json");
        if (null == in) {
            return null;
        }
        try {
            return mapper.readValue(in, JSONSchemaProps.class);
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    public static void main(String[] args) {
        JSONSchemaProps schema = readSchema();

        CustomResourceDefinitionBuilder builder = new CustomResourceDefinitionBuilder()
                .withApiVersion("apiextensions.k8s.io/v1beta1")
                .withNewMetadata().withName("sparkclusters.radanalytics.io")
                .endMetadata()
                .withNewSpec()
                .withNewNames()
                .withKind("SparkCluster")
                .endNames()
                .withGroup("radanalytics.io")
                .withVersion("v1")
                .withScope("Namespaced")
                .withNewValidation()
                .withNewOpenAPIV3SchemaLike(schema)
                .endOpenAPIV3Schema()
                .endValidation()
                .endSpec();

        new DefaultKubernetesClient().customResourceDefinitions().createOrReplace(builder.build());
    }
}
```

content of `sparkCluster.json`:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A Spark cluster configuration",
  "dependencies": null,
  "type": "object",
  "extends": {
    "type": "object",
    "existingJavaType": "io.radanalytics.operator.common.EntityInfo"
  },
  "properties": {
    "master": {
      "type": "object",
      "properties": {
        "instances": {
          "type": "integer",
          "default": "1",
          "minimum": "1"
        },
        "memory": {
          "type": "string"
        },
        "cpu": {
          "type": "string"
        },
        "labels": {
          "existingJavaType": "java.util.Map<String,String>",
          "type": "string",
          "pattern": "([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]"
        },
        "command": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "commandArgs": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "worker": {
      "type": "object",
      "properties": {
        "instances": {
          "type": "integer",
          "default": "1",
          "minimum": "0"
        },
        "memory": {
          "type": "string"
        },
        "cpu": {
          "type": "string"
        },
        "labels": {
          "existingJavaType": "java.util.Map<String,String>",
          "type": "string",
          "pattern": "([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]"
        },
        "command": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "commandArgs": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "customImage": {
      "type": "string"
    },
    "metrics": {
      "type": "boolean",
      "default": "false"
    },
    "sparkWebUI": {
      "type": "boolean",
      "default": "true"
    },
    "sparkConfigurationMap": {
      "type": "string"
    },
    "env": {
      "type": "array",
      "items": {
        "type": "object",
        "javaType": "io.radanalytics.types.Env",
        "properties": {
          "name": { "type": "string" },
          "value": { "type": "string" }
        },
        "required": ["name", "value"]
      }
    },
    "sparkConfiguration": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "value": { "type": "string" }
        },
        "required": ["name", "value"]
      }
    },
    "labels": {
      "type": "object",
      "existingJavaType": "java.util.Map<String,String>"
    },
    "historyServer": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "default": "sharedVolume",
          "enum": [
            "sharedVolume",
            "remoteStorage"
          ],
          "javaEnumNames": [
            "sharedVolume",
            "remoteStorage"
          ]
        },

        "sharedVolume": {
          "type": "object",
          "properties": {
            "size": {
              "type": "string",
              "default": "0.3Gi"
            },
            "mountPath": {
              "type": "string",
              "default": "/history/spark-events"
            },
            "matchLabels": {
              "type": "object",
              "existingJavaType": "java.util.Map<String,String>"
            }
          }
        },
        "remoteURI": {
          "type": "string",
          "description": "s3 bucket or hdfs path"
        }
      }
    },
    "downloadData": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string"
          },
          "to": {
            "type": "string"
          }
        },
        "required": [
          "url",
          "to"
        ]
      }
    }
  },
  "required": []
}
```

..but it would fail with any schema, even smaller one. Thanks for looking into this!

**Comment by rohanKanojia** [comment]
Hmm, I tried reproducing your issue. When I run this example, I get this error:
```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.42.184:8443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions. Message: CustomResourceDefinition.apiextensions.k8s.io "crontabs.stable.example.com" is invalid: spec.validation.openAPIV3Schema.dependencies: Forbidden: dependencies is not supported. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.validation.openAPIV3Schema.dependencies, message=Forbidden: dependencies is not supported, reason=FieldValueForbidden, additionalProperties={})], group=apiextensions.k8s.io, kind=CustomResourceDefinition, name=crontabs.stable.example.com, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=CustomResourceDefinition.apiextensions.k8s.io "crontabs.stable.example.com" is invalid: spec.validation.openAPIV3Schema.dependencies: Forbidden: dependencies is not supported, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:483)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:422)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:386)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:349)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:232)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:735)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:325)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:321)
	at io.fabric8.CustomResourceSchemaValidation.main(CustomResourceSchemaValidation.java:43)
```

Surprisingly, when I load it from a yaml, creation works :confused: : 
```
 KubernetesClient client2 = new DefaultKubernetesClient();
 CustomResourceDefinition crd2 = client.customResourceDefinitions().load(CustomResourceSchemaValidation.class.getResourceAsStream("/my-custom-resource-file.yml")).get();
 client.customResourceDefinitions().create(crd2);
```

Need to check how can we change this behavior of object mapper

**Comment by Jiri-Kremser** [comment]
yes, ^ that's that same error I was getting

**Comment by jkremser** [comment]
Any progress here?

> Need to check how can we change this behavior of object mapper


btw. I hit another similar issue, where I had to change the behavior of the default object mapper, and this helped:

```java
Serialization.jsonMapper().configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```

**Comment by saturnism** [comment]
i ran into the same issue :(

**Comment by jorsol** [comment]
Same issue here :(
 ```java
public static final CustomResourceDefinition CR_DEFINITION =
      new CustomResourceDefinitionBuilder()
          .withApiVersion("apiextensions.k8s.io/v1beta1")
          .withNewMetadata()
          .withName(NAME)
          .endMetadata()
          .withNewSpec()
          .withGroup(GROUP)
          .withVersion(VERSION)
          .withScope("Namespaced")
          .withNewNames()
          .withKind(KIND)
          .withListKind(KIND + "List")
          .withSingular(SINGULAR)
          .withPlural(PLURAL)
          .endNames()
          .withValidation(getSchemaValidation())
          .endSpec()
          .build();

  private static CustomResourceValidation getSchemaValidation() {
    Map<String, JSONSchemaProps> properties = new HashMap<>();
    properties.putIfAbsent("version", new JSONSchemaPropsBuilder()
        .withType("integer")
        .withMinimum(11d)
        .build());
    properties.putIfAbsent("conf", new JSONSchemaPropsBuilder()
        .withType("object")
        .build());

    Map<String, JSONSchemaProps> spec = new HashMap<>();
    spec.putIfAbsent("spec", new JSONSchemaPropsBuilder()
        .withRequired(properties.keySet().stream().collect(Collectors.toList()))
        .withProperties(properties)
        .build());

    return new CustomResourceValidationBuilder()
        .withOpenAPIV3Schema(new JSONSchemaPropsBuilder()
            .withRequired("spec")
            .withProperties(spec)
            .build())
        .build();
  }
```

This creates the following yaml:
```
apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  annotations: {}
  labels: {}
  name: "configs.demo.io"
spec:
  group: "demo.io"
  names:
    kind: "Config"
    listKind: "ConfigList"
    plural: "configs"
    singular: "config"
  scope: "Namespaced"
  validation:
    openAPIV3Schema:
      definitions: {}
      dependencies: {}
      patternProperties: {}
      properties:
        spec:
          definitions: {}
          dependencies: {}
          patternProperties: {}
          properties:
            conf:
              definitions: {}
              dependencies: {}
              patternProperties: {}
              properties: {}
              type: "object"
            version:
              definitions: {}
              dependencies: {}
              minimum: 11.0
              patternProperties: {}
              properties: {}
              type: "integer"
          required:
          - "conf"
          - "version"
      required:
      - "spec"
  version: "v1alpha1"
```

And creating the CRD in K8s gives:
```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.99.106:8443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions. Message: CustomResourceDefinition.apiextensions.k8s.io "configs.demo.io" is invalid: [spec.validation.openAPIV3Schema.dependencies: Forbidden: dependencies is not supported, spec.validation.openAPIV3Schema.properties[spec].dependencies: Forbidden: dependencies is not supported, spec.validation.openAPIV3Schema.properties[spec].properties[conf].dependencies: Forbidden: dependencies is not supported, spec.validation.openAPIV3Schema.properties[spec].properties[version].dependencies: Forbidden: dependencies is not supported]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.validation.openAPIV3Schema.dependencies, message=Forbidden: dependencies is not supported, reason=FieldValueForbidden, additionalProperties={}), StatusCause(field=spec.validation.openAPIV3Schema.properties[spec].dependencies, message=Forbidden: dependencies is not supported, reason=FieldValueForbidden, additionalProperties={}), StatusCause(field=spec.validation.openAPIV3Schema.properties[spec].properties[conf].dependencies, message=Forbidden: dependencies is not supported, reason=FieldValueForbidden, additionalProperties={}), StatusCause(field=spec.validation.openAPIV3Schema.properties[spec].properties[version].dependencies, message=Forbidden: dependencies is not supported, reason=FieldValueForbidden, additionalProperties={})], group=apiextensions.k8s.io, kind=CustomResourceDefinition, name=sgpgconfigs.stackgres.io, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=CustomResourceDefinition.apiextensions.k8s.io "configs.demo.io" is invalid: [spec.validation.openAPIV3Schema.dependencies: Forbidden: dependencies is not supported, spec.validation.openAPIV3Schema.properties[spec].dependencies: Forbidden: dependencies is not supported, spec.validation.openAPIV3Schema.properties[spec].properties[conf].dependencies: Forbidden: dependencies is not supported, spec.validation.openAPIV3Schema.properties[spec].properties[version].dependencies: Forbidden: dependencies is not supported], metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
```

**Comment by jkremser** [comment]
@saturnism, @jorsol check my ugly workaround: https://github.com/jvm-operators/abstract-operator/blob/ddb89ad2b0eda8ec29121fc37a4de24a000588de/src/main/java/io/radanalytics/operator/common/crd/CrdDeployer.java#L71:L74

**Comment by rohanKanojia** [comment]
I remember I looked into this few months ago... Maybe there was some bug on model side itself or some problem after deserialization. Need to revisit this again .

**Comment by sbaier1** [comment]
I am applying @jkremser 's workaround currently and i am seeing a very strange issue: the CRD `createOrReplace()` is not idempotent anymore with some Kubernetes version.

I tried running my code with Docker's builtin Kubernetes (Version: `Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`) and upon initial creation the CRD gets created and everything works, but when running `createOrReplace()` a second time, i get the same old `is invalid: spec.validation.openAPIV3Schema.dependencies: Forbidden: dependencies is not supported` from k8s api... very strange.

according to okhttp logs the client queries for the existing resource twice and then proceeds to `PUT` a new CRD with the dependencies array set to empty again, even though at the time of calling `createOrReplace()` the dependencies field is set to null.

**Comment by sbaier1** [comment]
@rohanKanojia are you still aware of this? can't really find a workaround for this issue on new k8s versions anymore

**Comment by rohanKanojia** [comment]
ah, Yes. I forgot to take a look at this again.

**Comment by rohanKanojia** [comment]
@sbaier1: I think your issue is related to #1789 , now kubernetes api requires `metadata.resourceVersion` to be passed in updated object for patching. You should get it fixed in next release.

**Comment by sbaier1** [comment]
> @sbaier1: I think your issue is related to #1789 , now kubernetes api requires `metadata.resourceVersion` to be passed in updated object for patching. You should get it fixed in next release.

The error i described still happens with 4.6.1. It is pretty simple to reproduce, create a CRD using an openAPI validation schema, set dependencies to null and run `createOrReplace` twice. The error will occur in any recent Kubernetes version.

**Comment by rohanKanojia** [comment]
Have you tried creating CRD with the workaround I specified?

**Comment by sbaier1** [comment]
> Have you tried creating CRD with the workaround I specified?

Yes, it shows the same behavior. Here's a quick and dirty reproducer:

```java
ObjectMapper mapper = new ObjectMapper();
        final URL resource = CreateFailIT.class.getResource("/schema/test.json");

        final JSONSchemaProps jsonSchemaProps = mapper.readValue(resource, JSONSchemaProps.class);

        final CustomResourceDefinitionFluent.SpecNested<CustomResourceDefinitionBuilder> crdBuilder = new CustomResourceDefinitionBuilder()
                .withApiVersion("apiextensions.k8s.io/v1beta1")
                .withNewMetadata()
                .withName("somethings.example.com")
                .endMetadata()
                .withNewSpec()
                .withNewNames()
                .withKind("Example")
                .withPlural("somethings")
                .withShortNames(Arrays.asList("ex")).endNames()
                .withGroup("example.com")
                .withVersion("v1")
                .withScope("Namespaced");
        final CustomResourceDefinition customResourceDefinition = crdBuilder
                .withNewValidation()
                .endValidation()
                .endSpec()
                .build();
        // Original workaround, same behavior
        //customResourceDefinition.getSpec().getValidation().getOpenAPIV3Schema().setDependencies(null);

        // just to make sure dependencies field is really null
        jsonSchemaProps.setDependencies(null);
        customResourceDefinition.getSpec().getValidation().setOpenAPIV3Schema(jsonSchemaProps);


        // To make this test idempotent
        client.customResourceDefinitions().delete(customResourceDefinition);
        do {
            System.out.println("Waiting until CRD is gone from K8s");
            Thread.sleep(500);
        } while (client.customResourceDefinitions().list()
                .getItems()
                .stream()
                .anyMatch(crd -> crd.getMetadata().getName().contains("somethings")));

        client.customResourceDefinitions().createOrReplace(customResourceDefinition);
        // This will always fail
        client.customResourceDefinitions().createOrReplace(customResourceDefinition);
```

**Comment by rohanKanojia** [comment]
@sbaier1 : You're right. I'm able to reproduce this during `createOrReplace()`. When I debugged this, I saw builder coming into action and converting a `null` object to `LinkedHashMap` here:

https://github.com/fabric8io/kubernetes-client/blob/c6f4d840df01158fdf5f3847557b6050ee07733c/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L105
