### ISSUE TITLE
Use diamond operator (`<>`) wherever possible

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#3163]
We're already on Java 8 and we can use this diamond operator which was introduced in Java 7. Yet, there are lots of occurrences in code where we're still not using it. For more information about this, see this Sonar rule[0]

In case anyone is interested in fixing this, you can check all the occurrences where diamond operator could be used here[1]

[0] https://sonarcloud.io/organizations/fabric8io/rules?open=java%3AS2293&rule_key=java%3AS2293
[1] https://sonarcloud.io/organizations/fabric8io/issues?projects=fabric8io_kubernetes-client&resolved=false&rules=java%3AS2293

**Comment by theexplorist** [comment]
@rohanKanojia Assign me this please!

**Comment by AvineshTripathi** [comment]
@rohanKanojia i wanna work on this issue, being a newbie can you help me in this ?

**Comment by rohanKanojia** [comment]
@AvineshTripathi : oh, unfortunately someone else picked up this issue. Shall I create another one for you?

**Comment by AvineshTripathi** [comment]
@rohanKanojia sure i would love to work but thing is I m a newbie with knowledge of java and a very little about docker and kubernetes so if you can help me get into contributions  that would be really appreciated ..

**Comment by ps-19** [comment]
@rohanKanojia is this resolved?
Can i work on this issue? If no can you assign one for me.

**Comment by theexplorist** [comment]
> @rohanKanojia is this issue resolved?
> Can i work on this issue? If no, can you assign one for me.

I am working on it, you can check the assigned tag above!

**Comment by ps-19** [comment]
@theexplorist thank you for you response, if you need any help in completion i can help you as a friend.

**Comment by rohanKanojia** [comment]
@ps-19 : You can pick some other issue if you want https://github.com/fabric8io/kubernetes-client/issues/3086

**Comment by ps-19** [comment]
Anyone need any help??

**Comment by Shatakshi0805** [comment]
Can I work on this?

**Comment by rohanKanojia** [comment]
@Shatakshi0805 : I'm sorry for the late reply. I was on PTO. I have created some extra issues. Could you please check if you can pick one of these:

https://github.com/fabric8io/kubernetes-client/labels/good%20first%20issue

**Comment by Shatakshi0805** [comment]
That's not a problem. yes, I will definitely check these issues. Thanks!

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?

**Comment by soham283** [comment]
it this issue has been solved ??

**Comment by rohanKanojia** [comment]
@soham283 : I think all places are still not updated: https://sonarcloud.io/organizations/fabric8io/issues?projects=fabric8io_kubernetes-client&resolved=false&rules=java%3AS2293

**Comment by soham283** [comment]
Then İ would like to work on this issue

**Comment by aadityasinha-dotcom** [comment]
I had already made a pr for this. Can anyone review that?

**Comment by soham283** [comment]
any updates is this issue has been solved or not ?

**Comment by rohanKanojia** [comment]
There are still places where this needs to be fixed. You can see files affected here:

https://sonarcloud.io/issues?severities=MINOR
(Ctrl + F diamond) and you'll see highlighted places

**Comment by Ashyum** [comment]
can I work on this issue?

**Comment by soham283** [comment]
@Ashyum issue is assigned to me it will be great if you can find another issue to work on, since I am following this issue from 2-3 months approx

**Comment by mhammadsaani** [comment]
Hey @rohanKanojia, is this issues solved or work needed on this?
If not then i would love to work on this!

**Comment by rohanKanojia** [comment]
There are still some places where we need to fix this

https://github.com/fabric8io/kubernetes-client/blob/master/extensions/certmanager/model-v1/src/main/java/io/fabric8/certmanager/api/model/v1/CertificateRequestSpec.java

https://github.com/fabric8io/kubernetes-client/blob/master/extensions/certmanager/model-v1beta1/src/main/java/io/fabric8/certmanager/api/model/v1beta1/CertificateRequestSpec.java

https://github.com/fabric8io/kubernetes-client/blob/master/extensions/certmanager/model-v1/src/main/java/io/fabric8/certmanager/api/model/acme/v1/ACMEChallengeSolverHTTP01Ingress.java

https://github.com/fabric8io/kubernetes-client/blob/master/extensions/certmanager/model-v1beta1/src/main/java/io/fabric8/certmanager/api/model/acme/v1beta1/ACMEChallengeSolverHTTP01Ingress.java

https://github.com/fabric8io/kubernetes-client/blob/master/extensions/istio/model-v1alpha3/src/main/java/io/fabric8/istio/api/networking/v1alpha3/CorsPolicy.java

Would be awesome if you could fix this if you get time

**Comment by mhammadsaani** [comment]
Yep, sure!
I will work on this.

**Comment by mhammadsaani** [comment]
Just to clear my mind, I have to do this,
if it is something like this:
 List<String> usages = new ArrayList<String>()
I have to make it look like
 private List<String> usages = new ArrayList<>()

**Comment by rohanKanojia** [comment]
Yes, you're right. You can take a look into Sonar Rule description[0]

[0] https://sonarcloud.io/organizations/fabric8io/rules?open=java%3AS2293&rule_key=java%3AS2293

**Comment by mhammadsaani** [comment]
> Yes, you're right. You can take a look into Sonar Rule description[0]
> 
> [0] https://sonarcloud.io/organizations/fabric8io/rules?open=java%3AS2293&rule_key=java%3AS2293

Yes, assign this to me @rohanKanojia
