### ISSUE TITLE
Private configuration classes cause trouble with Java native (reflection)

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#4724]
From https://github.com/quarkusio/quarkus/pull/30153

Some configuration classes (referenced issue is about `ExecConfig` but maybe there are more) have private access and need to be referenced by name in order to register them for reflection with GraalVM.

These classes should be exposed. In addition, it would be interesting to catalog these classes with an interface or something else, so that they can be automatically detected (Jandex) to be registered when used.

**Comment by rohanKanojia** [comment]
At the moment I see these private classes in KubernetesClient related modules:

- [Config.ExecCredential](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L861)
- [Config.ExecCredentialSpec](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L869)
- [Config.ExecCredentialStatus](https://github.com/fabric8io/kubernetes-client/blob/d15bb1dbb250c4367ffe1248e9734fdf5b358fbd/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L873)
- [HttpClientUtils.HeaderInterceptor](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java#L49)
- [RunOperations.RunConfigNestedImpl](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/run/RunOperations.java#L31)
- [URLFromNodePortImpl.NodePortUrlComponents](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/impl/URLFromNodePortImpl.java#L72)
- [KubernetesClientException.RequestMetadata](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java#L191)
- [Readiness.ReadinessHolder](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/readiness/Readiness.java#L51)
- [BackwardsCompatibilityInterceptor.ResourceKey](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/BackwardsCompatibilityInterceptor.java#L56)
- [PatchUtils.SingletonHolder](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PatchUtils.java#L40)

Do you think it makes sense to make these public?
- [Config.ExecCredential](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L861)
- [Config.ExecCredentialSpec](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L869)
- [Config.ExecCredentialStatus](https://github.com/fabric8io/kubernetes-client/blob/d15bb1dbb250c4367ffe1248e9734fdf5b358fbd/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L873)
- [RunOperations.RunConfigNestedImpl](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/run/RunOperations.java#L31)

**Comment by rohanKanojia** [comment]
@manusa : What else needs to be done in order to close this issue? I didn't add any interface because there were only three classes.

**Comment by manusa** [comment]
> @manusa : What else needs to be done in order to close this issue? I didn't add any interface because there were only three classes.

You did list a few other classes too in your comment. Are those classes accessible by users? are they susceptible to be serialized/deserialized?

**Comment by rohanKanojia** [comment]
They are private static classes but they are not configuration classes. I don't think it makes sense to make them accessible to users.

**Comment by manusa** [comment]
are they susceptible to be serialized/deserialized? ----> Are they accessible from Config?

**Comment by rohanKanojia** [comment]
No, these classes do not seem to be accessible from `io.fabric8.kubernetes.client.Config`

**Comment by manusa** [comment]
Addressed in Quarkus with https://github.com/quarkusio/quarkus/pull/31781. Closing issue.

**Comment by tomslot** [comment]
Still occurring with the latest lib version (6.8.0), only when run on Java 17, works well on Java 11

**Comment by tomslot** [comment]
The bug is located in io.fabric8.kubernetes.client.Config.getExecCredentialFromExecConfig():
The library is trying to parse a plain string error message output from ProcessBuilder as ExecCredential json.
The ProcessBuilder is executing the following command:
/usr/local/bin/aws --region XXX eks get-token --cluster-name YYY --output json

And the output is

"The SSO session associated with this profile has expired or is otherwise invalid. To refresh this SSO session run aws sso login with the corresponding profile."

Feel free to create a new ticket if it serves your process better.

**Comment by tomslot** [comment]
probably with Java 11 the string is parsed to null and with Java 17 it throws an exception

**Comment by rohanKanojia** [comment]
@tomslot : Sorry but from your comment, I think it's a different issue from this one. Is it possible to create a new ticket?

**Comment by tomslot** [comment]
I've just created https://github.com/fabric8io/kubernetes-client/issues/5361.
I got here from another ticket, which described my problem and was a supposed duplicate of this issue.
