### ISSUE TITLE
CI : OpenShift E2E workflow failing due to `openshift/origin-control-plane` image no longer present on Docker Hub

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#5545]
### Is your task related to a problem? Please describe

Since past week, I've seen E2E failures for OpenShift workflows on pull requests. All of them seem to fail in the setup phase:
```
Checking if image openshift/origin-control-plane:v3.11 is available ...
Pulling image openshift/origin-control-plane:v3.11
error: error pulling Docker image openshift/origin-control-plane:v3.11
Error: Command failed: oc cluster up --routing-suffix="127.0.0.1.${OC_DOMAIN:-nip.io}" 
    at checkExecSyncError (node:child_process:861:11)
Error: Command failed: oc cluster up --routing-suffix="127.0.0.1.${OC_DOMAIN:-nip.io}" 
    at Object.execSync (node:child_process:932:15)
    at logExecSync (/home/runner/work/_actions/manusa/actions-setup-openshift/v1.1.5/src/exec.js:8:17)
    at clusterUp (/home/runner/work/_actions/manusa/actions-setup-openshift/v1.1.5/src/install.js:16:3)
    at startCluster (/home/runner/work/_actions/manusa/actions-setup-openshift/v1.1.5/src/install.js:[18](https://github.com/fabric8io/kubernetes-client/actions/runs/6626026544/job/17998541125?pr=5540#step:4:19):39)
    at install (/home/runner/work/_actions/manusa/actions-setup-openshift/v1.1.5/src/install.js:46:3)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/home/runner/work/_actions/manusa/actions-setup-openshift/v1.1.5/src/index.js:16:3) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 70741,
  stdout: null,
  stderr: null
}
Error: Command failed: oc cluster up --routing-suffix="1[27](https://github.com/fabric8io/kubernetes-client/actions/runs/6626026544/job/17998541125?pr=5540#step:4:28).0.0.1.${OC_DOMAIN:-nip.io}"
```

It's due to [openshift/origin-control-plane](https://hub.docker.com/u/openshift/origin-control-plane) image no longer present on Docker Hub anymore.

### Describe the solution you'd like

We need to find out why this workflow started failing all of sudden and fix it.

**Comment by manusa** [comment]
It's more than that. That part is already fixed (https://github.com/manusa/actions-setup-openshift/pull/41).

However, the newer images don't seem to be working either.

**Comment by rohanKanojia** [comment]
[openshift/origin-control-plane](https://hub.docker.com/u/openshift/origin-control-plane) image are back on Docker Hub. However, OpenShift 3.11.0 build is still failing.

**Comment by manusa** [comment]
> [openshift/origin-control-plane](https://hub.docker.com/u/openshift/origin-control-plane) images are back on Docker Hub. However, OpenShift 3.11.0 build is still failing.

> [However, the newer images don't seem to be working either.](https://github.com/fabric8io/kubernetes-client/issues/5545#issuecomment-1778482988)

Only the proper 3.10 images have been restored in either Quay or Docker.

**Comment by manusa** [comment]
The issue should be considered now as complete.

We have now on-demand CI checks performed on an ephemeral OpenShift 3.10 cluster.
In addition, we've set up a CI pipeline that performs checks on a 4.x cluster provided by OSCI.io.
