### ISSUE TITLE
JsonMappingException after upgrading to Jackson 2.19.0

### ISSUE THREAD

**Issue by iampratapak** [fabric8io/kubernetes-client#7129]
### Describe the bug

We are using the Fabric8 Kubernetes client version 6.13.5 and are encountering the following error after upgrading Jackson to version 2.19.0

`
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: io.fabric8.kubernetes.api.model.GenericKubernetesResource["metadata"]->io.fabric8.kubernetes.api.model.ObjectMeta["managedFields"]->java.util.ArrayList[0]->io.fabric8.kubernetes.api.model.ManagedFieldsEntry["fieldsV1"]->io.fabric8.kubernetes.api.model.FieldsV1["getAdditionalProperties"]->java.util.LinkedHashMap["f:metadata"])
`

same as [Jackson 2.19.0 issues #7036
](https://github.com/fabric8io/kubernetes-client/issues/7036)

### Fabric8 Kubernetes Client version

6.13.5

### Steps to reproduce

- Upgraded Jackson to version 2.19.0
- Created a watch for a Custom Resource Definition (CRD)
- Encountering the following error on CRD create, update, or delete events

### Expected behavior

This error should not occur

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
io.fabric8.kubernetes.client.WatcherException: Unexpected exception processing watch event
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:390)
	at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:52)
	at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$1.onMessage(OkHttpWebSocketImpl.java:115)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base@24.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
	at java.base@24.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
	at java.base@24.0.1/java.lang.Thread.runWith(Thread.java:1460)
	at java.base@24.0.1/java.lang.Thread.run(Thread.java:1447)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808)
Caused by: java.lang.IllegalArgumentException: (was java.lang.NullPointerException) (through reference chain: io.fabric8.kubernetes.api.model.GenericKubernetesResource["metadata"]->io.fabric8.kubernetes.api.model.ObjectMeta["managedFields"]->java.util.ArrayList[0]->io.fabric8.kubernetes.api.model.ManagedFieldsEntry["fieldsV1"]->io.fabric8.kubernetes.api.model.FieldsV1["getAdditionalProperties"]->java.util.LinkedHashMap["f:metadata"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4663)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4594)
	at io.fabric8.kubernetes.client.utils.KubernetesSerialization.convertValue(KubernetesSerialization.java:371)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.eventReceived(AbstractWatchManager.java:287)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:377)
	... 14 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: io.fabric8.kubernetes.api.model.GenericKubernetesResource["metadata"]->io.fabric8.kubernetes.api.model.ObjectMeta["managedFields"]->java.util.ArrayList[0]->io.fabric8.kubernetes.api.model.ManagedFieldsEntry["fieldsV1"]->io.fabric8.kubernetes.api.model.FieldsV1["getAdditionalProperties"]->java.util.LinkedHashMap["f:metadata"])
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:324)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:810)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:763)
	at com.fasterxml.jackson.databind.ser.AnyGetterWriter.getAndSerialize(AnyGetterWriter.java:81)
	at com.fasterxml.jackson.databind.ser.AnyGetterWriter.serializeAsField(AnyGetterWriter.java:89)
	at io.fabric8.kubernetes.model.jackson.BeanPropertyWriterDelegate.serializeAsField(BeanPropertyWriterDelegate.java:68)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:760)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at io.fabric8.kubernetes.model.jackson.BeanPropertyWriterDelegate.serializeAsField(BeanPropertyWriterDelegate.java:68)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:760)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at io.fabric8.kubernetes.model.jackson.BeanPropertyWriterDelegate.serializeAsField(BeanPropertyWriterDelegate.java:68)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:760)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at io.fabric8.kubernetes.model.jackson.BeanPropertyWriterDelegate.serializeAsField(BeanPropertyWriterDelegate.java:68)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:760)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:503)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4641)
	... 18 more
Caused by: java.lang.NullPointerException
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:796)
	... 42 more
```

### Additional context

Client Version: v1.32.1
Kustomize Version: v5.5.0
Server Version: v1.31.1

**Comment by iampratapak** [comment]
@manusa Will the fix be included in a 6.13.x release, or do we need to upgrade to 7.3.x?

**Comment by manusa** [comment]
Same as #7107

Fixed an released in [v6.14.0](https://github.com/fabric8io/kubernetes-client/releases/tag/v6.14.0)

If you upgrade to Jackson 2.19.0 and want to remain in 6.x then you'll need to use at least 6.14.0.

> or do we need to upgrade to 7.3.x?

Note that 6 is just on maintenance mode and will only be updated for CVEs and broad impacting issues such as #7107.

**Comment by iampratapak** [comment]
Thanks @manusa ,

We will go with 6.14.0 in our current release. For the next release, we plan to move to 7.3.x

**Comment by zeroEntropyy** [comment]
Does only upgrading to 7.3.0 fixing the issue? 
I tried upgrading, but still getting similar error. 

I have configured my kubernetes client in this way, and then use this bean everywhere needed.

`
@Configuration
public class KubernetesClientConfigurer {
    
    @Bean
    public KubernetesClient kubernetesClient() {
        return new KubernetesClientBuilder().build();
    }

}
`

**Comment by iampratapak** [comment]
@zeroEntropyy 
In version `6.14.0` with Jackson `2.19.2`, we didn't see this issue. Also, with version `7.3.1` with Jackson `2.19.2`, we didn't see this issue.

Try upgrading to version `7.3.1`. We are using that version and haven't noticed this issue.
